---
title: "Assignment 5"
author: "Kundan Kumar"
date: "2024-04-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#question 1
library(rjags)
library(geoR) 
data(gambia) 

response_variable <- gambia$pos
covariates <- gambia[1:length(gambia$pos), -3]

data_list <- list(Y = response_variable, X = covariates, n = length(response_variable), p = dim(covariates)[2])

model_string <- ("model {
  
# Logistic regression 

for(i in 1:n){ 
 Y[i] ~ dbern(q[i]) 
 logit(q[i]) <- inprod(X[i,], beta[])  
} 

for(j in 1:p){
  beta[j] ~ dnorm(0,0.01)
}
    
}")

initial_values <- list(beta = rep(0, 7))
model <- jags.model(textConnection(model_string), data = data_list, inits = initial_values, n.chains = 2)

# Burn-in for 5000 samples 
update(model, 1000)

samples <- coda.samples(
  model,
  variable.names = c("beta"),
  n.iter = 5000,
  progress.bar = "none"
)

summary(samples)





#part b


unique_locations <- c(1)
count <- 1

for(i in 2:length(gambia$x)){
  if(gambia$x[i] != gambia$x[i-1]){
    count <- count + 1
  }
  unique_locations <- c(unique_locations, count)
}

response_variable <- gambia$pos
covariates <- gambia[1:length(gambia$pos), -3]

data_list <- list(Y = response_variable, X = covariates, n = length(response_variable), p = dim(covariates)[2], s = unique_locations)

model_string <- ("model {
  
# Random effects logistic regression 

for(i in 1:n){ 
 Y[i] ~ dbern(q[i]) 
 logit(q[i]) <- inprod(X[i,], beta[]) + alpha[s[i]]
} 

for(j in 1:65){
  alpha[j] ~ dnorm(0, tau_sq_inv)
}

for(j in 1:p){
  beta[j] ~ dnorm(0,0.01)
}

tau_sq_inv ~ dgamma(0.1,0.1)
    
}")

initial_values <- list(beta = rep(0, 7), tau_sq = rnorm(1))
model <- jags.model(textConnection(model_string), data = data_list, inits = initial_values, n.chains = 2)

# Burn-in for 5000 samples 
update(model, 1000, progress.bar = "none")

samples <- coda.samples(
  model,
  variable.names = c("beta", "tau_sq"),
  n.iter = 5000,
  progress.bar = "none"
)

summary(samples)

```
```{r}
#Question 2
library(MASS)
data("galaxies")
galaxies_Y <- galaxies
hist(galaxies_Y, breaks = 25)
n <- length(galaxies_Y)

galaxies_data <- list(Y = galaxies_Y, N = n, K = 3, alpha = rep(1, 3))

library(rjags)
model_string <- textConnection("model{

# Likelihood
for (i in 1:N) {
  Y[i] ~ dnorm(mu[Z[i]], tau[Z[i]])
  
  Z[i] ~ dcat(theta[])
}

for (j in 1:K) {
  mu[j] ~ dnorm(0, 1e-8) 
  tau[j] ~ dgamma(0.01, 0.01)
}
theta[1:K] ~ ddirch(alpha[])
}")

params <- c('mu', 'tau', 'theta')

model <- jags.model(model_string, data = galaxies_data, quiet = TRUE)
update(model, 2e4)

samples <- coda.samples(model, variable.names = params, n.iter = 1e4) 
plot(samples[[1]][,1])
plot(samples[[1]][,2])
plot(samples[[1]][,3])

y <- seq(5000, 40000, 100)

mu_post <- samples[[1]][,1:3]
tau_post <- samples[[1]][,4:6]
theta_post <- samples[[1]][,7:9]

S <- 1e4

post_density <- matrix(NA, nrow = S, ncol = 351)

for(i in 1:S) {
  mu <- as.numeric(mu_post[i,])
  sigma <- as.numeric(1 / sqrt(tau_post[i,]))
  theta <- as.numeric(theta_post[i, ])
  
  mix_gauss <- function(x) {
    theta[1] * dnorm(x, mean = mu[1], sd = sigma[1]) +
      theta[2] * dnorm(x, mean = mu[2], sd = sigma[2]) + 
      theta[3] * dnorm(x, mean = mu[3], sd = sigma[3])
  }
  
  post_density[i, ] <- sapply(y, mix_gauss)
  
  print(paste0('Done:', i))
}

post_median <- apply(post_density, 2, median)
post_2.5_quantile <- apply(post_density, 2, quantile, probs = 0.025)
post_97.5_quantile <- apply(post_density, 2, quantile, probs = 0.975)

par(mfrow = c(1,1))

library(ggplot2)

ggplot() +
  geom_histogram(aes(x = galaxies_Y, y = after_stat(density)), col = 'black') +
  geom_line(aes(y, post_median, col = 'Median'), size = 1) +
  geom_line(aes(y, post_2.5_quantile, col = 'Quantile: 0.025'), linetype = 'dashed', size = 1) +
  geom_line(aes(y, post_97.5_quantile, col = 'Quantile: 0.975'), linetype = 'dashed', size = 1) +
  labs(col='Index')

```
```{r}
#question 3

set.seed(100)
library(rjags)
library(kableExtra)

Y1_mr_october <- 563
Y2_mr_october <- 10

N1_mr_october <- 2820
N2_mr_october <- 27

Y_mr_october <- c(563, 10)
N_mr_october <- c(2820, 27)



# Model M1: Two Poisson distributions
model_string_m1 <- "model{
 # Likelihood
 for(i in 1:length(N_mr_october))
 {
  Y_mr_october[i] ~ dpois(N_mr_october[i]*lambda[i])
 }
 
 # Priors
 c_value_m1 <- 1
 lambda1 ~ dunif(0, c_value_m1)
 lambda2 ~ dunif(0, c_value_m1)
 
 lambda <- c(lambda1, lambda2)
}"

# Model M2: Single Poisson distribution
model_string_m2 <- "model{
 # Likelihood
 for(i in 1:length(N_mr_october))
 {
  Y_mr_october[i] ~ dpois(N_mr_october[i]*lambda0_m2)
 }
 
 # Priors
 c_value_m2 <- 1
 lambda0_m2 ~ dunif(0, c_value_m2)
 lambda_m2 <- lambda0_m2
}"

data_mr_october <- list(Y_mr_october = Y_mr_october, N_mr_october = N_mr_october)

# Model M1 fitting
model_m1 <- jags.model(textConnection(model_string_m1),
                       data = data_mr_october, n.chains = 1, quiet = TRUE)
update(model_m1, 10000, progress.bar = "none")
sample_m1 <- coda.samples(model_m1, variable.names = c("lambda"),
                          n.iter = 20000, thin = 5, progress.bar = "none")
lambda_m1 <- sample_m1[[1]]

# Model M2 fitting
model_m2 <- jags.model(textConnection(model_string_m2),
                       data = data_mr_october, n.chains = 1, quiet = TRUE)
update(model_m2, 10000, progress.bar = "none")
sample_m2 <- coda.samples(model_m2, variable.names = c("lambda0_m2"),
                          n.iter = 20000, thin = 5, progress.bar = "none")

lambda_m2 <- sample_m2[[1]]

# After thinning, 4000 post-burn-in samples left for each model
loglike_m1 <- sapply(1:4000, function(iter) {
  sum(dpois(Y1_mr_october, lambda = lambda_m1[iter, 1], log = TRUE) + dpois(Y2_mr_october, lambda = lambda_m1[iter, 2], log = TRUE))
})
loglike_m2 <- sapply(1:4000, function(iter) {
  sum(dpois(Y1_mr_october, lambda = lambda_m2[iter, 1], log = TRUE) + dpois(Y2_mr_october, lambda = lambda_m2[iter, 1], log = TRUE))
})

deviance_m1 <- -2 * loglike_m1
deviance_m2 <- -2 * loglike_m2

# DIC calculation
Dbar_m1 <- mean(deviance_m1)
Dbar_m2 <- mean(deviance_m2)

D_thetahat_m1 <- sum(dpois(Y1_mr_october, lambda = mean(lambda_m1[, 1]), log = TRUE) + dpois(Y2_mr_october, lambda = mean(lambda_m1[, 2]), log = TRUE))
D_thetahat_m2 <- sum(dpois(Y1_mr_october, lambda = mean(lambda_m2[, 1]), log = TRUE) + dpois(Y2_mr_october, lambda = mean(lambda_m2[, 1]), log = TRUE))

pD_m1 <- Dbar_m1 - D_thetahat_m1
pD_m2 <- Dbar_m2 - D_thetahat_m2
DIC_m1 <- pD_m1 + Dbar_m1
DIC_m2 <- pD_m2 + Dbar_m2

# WAIC calculation
loglike1_m1 <- sapply(1:4000, function(iter) {
  dpois(Y1_mr_october, lambda = lambda_m1[iter, 1], log = TRUE)
})
loglike2_m1 <- sapply(1:4000, function(iter) {
  dpois(Y2_mr_october, lambda = lambda_m1[iter, 2], log = TRUE)
})
loglike1_m2 <- sapply(1:4000, function(iter) {
  dpois(Y1_mr_october, lambda = lambda_m2[iter, 1], log = TRUE)
})
loglike2_m2 <- sapply(1:4000, function(iter) {
  dpois(Y2_mr_october, lambda_m2[iter, 1], log = TRUE)
})

posmeans_m1 <- c(mean(loglike1_m1), mean(loglike2_m1))
posmeans_m2 <- c(mean(loglike1_m2), mean(loglike2_m2))
posvars_m1 <- c(var(loglike1_m1), var(loglike2_m1))
posvars_m2 <- c(var(loglike1_m2), var(loglike2_m2))
pW_m1 <- sum(posvars_m1)
pW_m2 <- sum(posvars_m2)
sum_means_m1 <- sum(posmeans_m1)
sum_means_m2 <- sum(posmeans_m2)
WAIC_m1 <- -2 * sum_means_m1 + 2 * pW_m1
WAIC_m2 <- -2 * sum_means_m2 + 2 * pW_m2

# Creating output table
OUT_mr_october <- rbind(c(DIC_m1, WAIC_m1), c(DIC_m2, WAIC_m2))
OUT_mr_october <- round(OUT_mr_october, 2)
rownames(OUT_mr_october) <- c("Model1", "Model2")
colnames(OUT_mr_october) <- c("DIC", "WAIC")

# Displaying the output table
kable(OUT_mr_october)
```
```{r}
#question4

library(rjags)
library(geoR)
data("gambia")

observed_response = gambia$pos
predictor_matrix = gambia[,4:8]
num_obs = length(observed_response)
num_predictors = ncol(predictor_matrix)



data_list = list(Y = observed_response, n = num_obs, p = num_predictors, X = predictor_matrix)


model_string = "model{
       # Priors
      for(j in 1:p){
      beta[j] ~ dnorm(0, 1e-3)
      }
      
      # Likelihood
      for(i in 1:n){
      Y[i] ~ dbinom(probs[i], 1)
      logit(probs[i]) = inprod(X[i,], beta)
      }

      # PPC
      for(i in 1:n){
      Y_new[i] ~ dbinom(probs[i], 1)
      }
      coefficients = mean(Y_new[])
}"


parameters = c('coefficients')

model = jags.model(textConnection(model_string), data = data_list, quiet = TRUE)
update(model, 1500)

samples = coda.samples(model, variable.names = parameters, thin = 5, n.iter = 3000)
plot(samples)

observed_mean = mean(observed_response)
posterior_samples = samples[[1]]

library(ggplot2)

ggplot() +
  geom_density(aes(x = posterior_samples, y = after_stat(density)), color = 'red', size = 1) +
  geom_vline(aes(xintercept = observed_mean, col = 'Data'), size = 1) +
  labs(col = 'Index',
       title = 'Posterior Predictive Check',
       y = 'Posterior Probability') +
  scale_color_manual(values = c('Data'='orange'))
```